version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    labels: ["dependencies"]

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    labels: ["dependencies"]
