name: "Pull request"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "examples/**"
      - "LICENSE"
      - "**.md"

defaults:
  run:
    working-directory: "testing/pull_request"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    strategy:
      matrix:
        terraform: [1.0.0, 0.15.0, 0.14.0, 0.13.0]

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Download repository as module
        uses: actions/checkout@v2
        with:
          path: testing/pull_request/module

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        id: terraformApply
        run: terraform apply tfplan

      - name: Terraform destroy
        if: ${{ (success() && steps.terraformApply.outcome == 'success') || (failure() && steps.terraformApply.outcome == 'failure') }}
        run: terraform destroy -auto-approve
